### ISSUE TITLE
"System.ArgumentException: Campaign cover url cannot be null or empty"

### ISSUE THREAD

**Issue by senrath** [AlexCSDev/PatreonDownloader#100]
I saw that this error had been previously reported but was closed for not providing enough information ( #46 ).

When attempting to download from one of the Patreons I support (https://www.patreon.com/semeukee/posts) I get the following error:
2021-10-19 10:06:02.5757 INFO Retrieving cookies...
2021-10-19 10:06:07.0969 INFO Preparing to download...
2021-10-19 10:06:09.4605 INFO Crawling...
2021-10-19 10:06:09.4751 FATAL Fatal error, application will be closed: System.ArgumentException: Campaign cover url cannot be null or empty
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 62
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

Hopefully a link to a Patreon account that exhibits the issue is enough info.

**Comment by AlexCSDev** [comment]
Fixed in 0.10.1.2
