### ISSUE TITLE
Unable to retrive cookies

### ISSUE THREAD

**Issue by w-canvas** [AlexCSDev/PatreonDownloader#101]
I'm attempting to download content for the first time, but being unable to input my credentials. Web browser shows login page for 3 seconds then exits. Terminal returns the followig error:

```


$ ./PatreonDownloader.App --url https://www.patreon.com/artist-name/posts --download-directory /home/vapor/Downloads/patreon/test1
2021-10-30 20:46:40.7018 INFO Retrieving cookies...
2021-10-30 20:46:56.0068 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at PatreonDownloader.App.Program.InitializeSettings(CommandLineOptions commandLineOptions) in /home/vapor/Downloads/PatreonDownloader/PatreonDownloader.App/Program.cs:line 166
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in /home/vapor/Downloads/PatreonDownloader/PatreonDownloader.App/Program.cs:line 142
   at PatreonDownloader.App.Program.Main(String[] args) in /home/vapor/Downloads/PatreonDownloader/PatreonDownloader.App/Program.cs:line 69

```

I'm I doing something wrong?

I believe this was previousley mentioned on [issue #41](https://github.com/AlexCSDev/PatreonDownloader/issues/41) but was closed due to lack of response from the submitting part.

os: ubuntu 20.04.3
PatreonDownloader version: 0.10.1.2

**Comment by AlexCSDev** [comment]
I will try to find some time to check what is going on and get back to you

**Comment by enamoria** [comment]
Try to use the tarball for dotnet. The installation via snap or the script caused this error.

**Comment by w-canvas** [comment]
I originally installed the dotnet sdk using **apt**. Retried with the tarball **unsuccessfully**.

**Comment by AlexCSDev** [comment]
you don't need neither runtime nor sdk installed to run the app if you download it from releases tab

**Comment by w-canvas** [comment]
> You don't need neither runtime nor sdk installed to run the app if you download it from releases tab. Installing them should have no effect on the way application behaves as long as you use official binaries.
> 
> Generally I don't provide any support if you run the app from sources unless I can clearly see that the issue is in the code itself.

Yes, I did try the official binary. My previous comment was supposed to be a reply to enamora, but I forgot to quote the suggestion.

**Comment by yuukiw** [comment]
on my end it opens an instant of chromium that google says isnt safe and thus wont let me login.

**Comment by w-canvas** [comment]
Was able to extract the cookies form chomium using:
```
chromium --user-data-dir=/path/to/net5.0-linux-x64-release/chromedata --remote-debugging-port=9222 > /dev/null 2>&1 & (sleep 10; pkill chrome) &
/path/to/PatreonDownloader.App --url https://www.patreon.com/creator/posts --download-directory /path/to/content/ --remote-browser-address ws://127.0.0.1:9222
```

**Comment by w-canvas** [comment]
Was able to extract the cookies form chomium using:
```
chromium --remote-debugging-port=9222 > /dev/null 2>&1 & (sleep 10; pkill chrome) &
/path/to/PatreonDownloader.App \
    --url https://www.patreon.com/creatorName/posts \
    --download-directory /path/to/content/ \
    --remote-browser-address ws://127.0.0.1:9222
```

**Comment by shinji257** [comment]
I'm also using the official binary.  Tried both the Windows and Linux versions and both produce the error eventually.  On Windows version I ended up using a portable version of Chromium with the debug port enabled and that works for grabbing cookies.
