### ISSUE TITLE
[Bug] Embedded chromium is no longer considered "secure" when logging into Patreon using Google oauth

### ISSUE THREAD

**Issue by forever-and-a-day** [AlexCSDev/PatreonDownloader#108]
Image:
![no-oauth](https://user-images.githubusercontent.com/10383240/157780402-4e6c37b0-2e4e-49f6-83d9-3fd5f8b0bb4e.jpg)
While I doubt these are very useful, here is the output of my console after closing chromium:
`./PatreonDownloader.App --descriptions --embeds --json --campaign-images --url https://www.patreon.com/creator/posts
2022-03-10 16:52:08.1560 INFO Retrieving cookies...
2022-03-10 16:52:33.2613 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at PatreonDownloader.App.Program.InitializeSettings(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 166
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 142
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69`
[System info](https://gist.github.com/forever-and-a-day/517417d90a32a353d61376f8f402a80a) - let me know if there's any other logs that would help you diagnose the issue.

**Comment by AlexCSDev** [comment]
Was reported before: #102, also contains the information on how to get around this issue.

Not sure if it's possible to fix this issue.

**Comment by forever-and-a-day** [comment]
Ah, thanks. I searched the issues for "Google" real quick before I submitted this issue, but it looks like I needed to spell it wrong lol. Thanks for the info.
