### ISSUE TITLE
Issues downloading files ("Forbidden" status code) due to new anti-bot measures

### ISSUE THREAD

**Issue by matty** [AlexCSDev/PatreonDownloader#110]
I can see in the console it outputs "+ Media" and "+ File" but it doesn't download anything? Does it crawl first before downloading?

There is another issue with the crawler after a while it shows 404 Forbidden, I think Patreon is blocking due to too many requests so there needs to be a way to slow down the crawler or have a long / random wait time.

**Comment by aksskl** [comment]
I'm getting a FATAL error unable to retrieve data.

**Comment by shinji257** [comment]
The Forbidden message seems to be due to Patreon's own anti-bot measure kicking in.  It does mention one of the triggers now is "clicking" faster than humanly possible.  If I remove the chromedata folder and login again the first thing I get is a sliding captcha to complete.  After logging in the download (for that URL) works fine.

**Comment by matty** [comment]
Seems to be what @shinji257 said, looks like we need something to detect the anti-bot and open the browser to verify.

**Comment by aksskl** [comment]
Yeah, deleting the chromedata folder before each run and re-logging in seems to be the only way for now. I was also able to get it to work after a few hours of waiting.

**Comment by AlexCSDev** [comment]
I will need someone to post the example of that anti-bot thing because I have never encountered it myself.

**Comment by aksskl** [comment]
```
D:\downloads\net5.0-win-x64-release>PatreonDownloader.App.exe --url https://www.patreon.com/gamersnexus/posts --download-directory D:\downloads\gamersnexus --descriptions --embeds --campaign-images --json
2022-03-19 01:30:33.2533 INFO Retrieving cookies...
2022-03-19 01:30:37.2693 INFO Preparing to download...
2022-03-19 01:30:37.8622 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve campaign id: Unable to retrieve data from https://www.patreon.com/gamersnexus/posts: Error status code returned: Forbidden
 ---> UniversalDownloaderPlatform.Common.Exceptions.DownloadException: Unable to retrieve data from https://www.patreon.com/gamersnexus/posts: Error status code returned: Forbidden
 ---> System.Net.WebException: Error status code returned: Forbidden
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadStringInternal(String url, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 295
   --- End of inner exception stack trace ---
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadStringInternal(String url, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 341
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 260
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 36
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 49
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 24
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 176
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

D:\downloads\net5.0-win-x64-release>PAUSE
Press any key to continue . . .
```

This is what I'm encountering.

**Comment by AlexCSDev** [comment]
I need the screenshot of the anti-bot page

**Comment by aksskl** [comment]
> I need the screenshot of the anti-bot page

![botpage](https://user-images.githubusercontent.com/34887104/159102546-6c733109-b5bb-49b0-9bea-fe6f644cc63e.png)

**Comment by AlexCSDev** [comment]
Huh, this is the first time I see it. Does it get triggered during file downloading or only during crawling (+ Media, + File, ...) process?

**Comment by aksskl** [comment]
I only come across while logging in. The chrome window does not pop up while crawling or downloading. Only during first time logins.

**Comment by shinji257** [comment]
I've had it happen on crawling for larger patreons.

**Comment by theFra985** [comment]
I have a similar issue and I'm getting a 403 forbidden only when trying to start downloading with the program (but not when opening the pages manually from the browser).
I noticed Patreon added a new `datadome` attribute and I'm wondering if it could be related to the fact that both of my downloading script stopped working.
In my case is the `/api/posts` call that gives a 403 response directly

**Comment by SuperMarioSega** [comment]
> EDIT: Nevermind. Larger patreons seem to die mid-run so it will have to be a random wait built into the program.

Same here, it's only with large patreons that it fails, works just fine with smaller ones.

**Comment by AlexCSDev** [comment]
Alright, I think I have figured out the solution. The browser window will appear if captcha needs to be solved, this might happen more than once on big creators. 

This will probably completely break the ability for automation and running the app on headless machines, but there is just no other solution. Increased delays between the requests doesn't appear to help at all.

**Comment by AlexCSDev** [comment]
Should be fixed in 0.10.2.0. I don't have ability to test this extensively, so feel free to reopen this issue if it's not fixed completely.

**Comment by bt2901** [comment]
Does not appear to be fixed completely. A window appears, I do the CAPTCHA stuff, login goes fine, but the browser window stays open and no download progress is visible. If I close the browser window, I get 
```
2022-03-28 00:29:06.0314 FATAL Fatal error, application will be closed: PuppeteerSharp.NavigationException: Navigation failed because browser has disconnected! (Target.detachedFromTarget)
 ---> PuppeteerSharp.TargetClosedException: Navigation failed because browser has disconnected! (Target.detachedFromTarget)
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 91
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 121
   --- End of inner exception stack trace ---

   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 125
   at PatreonDownloader.PuppeteerEngine.Wrappers.Browser.WebPage.GoToAsync(String url, Nullable`1 timeout, WaitUntilNavigation[] waitUntil) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\Wrappers\Browser\WebPage.cs:line 34
   at PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver.SolveCaptcha(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCaptchaSolver.cs:line 59
   at PatreonDownloader.Implementation.PatreonWebDownloader.SolveCaptchaAndUpdateCookies(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 83
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 76
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 84
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69
```

**Comment by bt2901** [comment]
Oh, I just noticed that it works if you wait a couple of minutes: the browser window closes and the downloads continue.

**Comment by shinji257** [comment]
So I ran my first attempt with the new update but it doesn't seem to work.  At least that's what I thought anyways.  What happens is Patreon is moving on to the next page after you clear the captcha but the downloader doesn't seem to notice it however this last time I went back a page and it finally noticed and continued on.

So.... If the download seems to get stuck even though you completed the captcha try going back one page.  This includes both the times where it loads a page and the ones where you get an API error.

**Comment by Crystal-RainSlide** [comment]
Now the log loops like that:
```
WARN [DynamicInjector82a700b49c3d4a609e215fed463f82c0] Captcha has been triggered, the browser window will be opened now. Please solve the captcha there.
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Initializing PuppeteerEngine with parameters , True
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver] Calling captcha check
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver] Retrieving browser
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Opening new page
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Creating IWebBrowser
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver] Checking if captcha is returned
DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver] Captcha was not returned, done
```

**Comment by thurask** [comment]
I'm getting the captcha loop as well; the supplied Chromium opens to log in, but once logged in it never opens again for the captcha and the app keeps creating and killing Chromium instances:

```
2022-04-14 20:35:04.7664 DEBUG Universal Downloader Platform settings: SaveDescriptions=False,SaveEmbeds=False,SaveJson=False,SaveAvatarAndCover=False,DownloadDirectory=,OverwriteFiles=False,UseSubDirectories=False,MaxFilenameLength=100
2022-04-14 20:35:04.7664 INFO Preparing to download...
2022-04-14 20:35:05.6323 WARN Captcha has been triggered, the browser window will be opened now. Please solve the captcha there.
2022-04-14 20:35:05.6323 DEBUG Initializing PuppeteerEngine with parameters , True
2022-04-14 20:35:05.6715 DEBUG Found 34 chrome processes (not sure which one yet)
2022-04-14 20:35:05.6715 DEBUG Calling captcha check
2022-04-14 20:35:05.6715 DEBUG Retrieving browser
2022-04-14 20:35:05.6715 DEBUG Downloading browser
2022-04-14 20:35:05.6715 DEBUG Launching browser
2022-04-14 20:35:06.7006 DEBUG Opening new page
2022-04-14 20:35:06.7694 DEBUG Creating IWebBrowser
2022-04-14 20:35:06.8331 DEBUG Checking if captcha is returned
2022-04-14 20:35:14.0037 DEBUG Captcha was not returned, done
2022-04-14 20:35:14.0037 DEBUG Retrieving browser
2022-04-14 20:35:14.0037 DEBUG Retrieving cookies
2022-04-14 20:35:15.5688 DEBUG Adding cookie: datadome
2022-04-14 20:35:15.5688 DEBUG Adding cookie: patreon_locale_code
2022-04-14 20:35:15.5688 DEBUG Adding cookie: G_ENABLED_IDPS
2022-04-14 20:35:15.5688 DEBUG Adding cookie: _ALGOLIA
2022-04-14 20:35:15.5688 DEBUG Adding cookie: patreon_location_country_code
2022-04-14 20:35:15.5688 DEBUG Adding cookie: session_id
2022-04-14 20:35:15.5688 DEBUG Adding cookie: __cf_bm
2022-04-14 20:35:15.5688 DEBUG Adding cookie: patreon_device_id
2022-04-14 20:35:15.5688 DEBUG Disposing puppeteer engine
2022-04-14 20:35:16.1372 WARN Captcha has been triggered, the browser window will be opened now. Please solve the captcha there.
2022-04-14 20:35:16.1372 DEBUG Initializing PuppeteerEngine with parameters , True
2022-04-14 20:35:16.1738 DEBUG Found 35 chrome processes (not sure which one yet)
2022-04-14 20:35:16.1738 DEBUG 1 chrome processes are in patreondownloader's folder
2022-04-14 20:35:16.1738 WARN Running PatreonDownloader's Chrome detected. Attempting to close it...
2022-04-14 20:35:16.1738 DEBUG Attempting to kill PID 211876
2022-04-14 20:35:16.1738 INFO Successfully killed all PatreonDownloader's Chrome instances.
2022-04-14 20:35:16.1738 DEBUG Calling captcha check
2022-04-14 20:35:16.1738 DEBUG Retrieving browser
2022-04-14 20:35:16.1738 DEBUG Downloading browser
2022-04-14 20:35:16.1738 DEBUG Launching browser
2022-04-14 20:35:17.4552 DEBUG Opening new page
2022-04-14 20:35:17.5247 DEBUG Creating IWebBrowser
2022-04-14 20:35:17.5780 DEBUG Checking if captcha is returned
2022-04-14 20:35:19.2623 INFO Cancellation requested
2022-04-14 20:35:19.2623 DEBUG Cleanup called
2022-04-14 20:35:19.2623 DEBUG Disposing downloader...
^C
```

This happens regardless which pages I try. If I leave it running for long enough I get the same error as in #115 and some orphaned Chromium processes after the main program dies. Chromium 93.0.4577.0 (the one the app downloads) on Windows 11 x64 for what it's worth.

**Comment by shinji257** [comment]
I don't get the loop but if the captcha comes up during the initial connection (before it starts crawling) then I actually have to close the browser and restart the whole process at which point things more or less work ok.  One thing I've noticed is that I never get a captcha during downloading.  Only during the login or crawl phases.
