### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by w-canvas** [AlexCSDev/PatreonDownloader#118]
Updated to version 0.10.2.0 after noticing application process was being interrupted.

Patreon login screen on PatreonDownloader Chromium (v93) returns the error `Something went wrong. We were unable to create or login to your account.` when attempting a cookie login.

Alternatively, regular Chromium (v100) is able to login correctly with remote debugging enabled, and PatreonDownloader executes for exactly 2 minutes; then, the Patreon interface in chromium prompts a jigsaw captcha and the download process is interrupted with the following error:

```
2022-04-01 08:03:13.4127 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.DownloadException: Error status code returned: BadRequest
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadStringInternal(String url, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 377
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 289
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 76
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 76
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 76
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 84
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69
```

No files are downloaded.

Context:

For normal usage I'm running the commands:

```
${PatreonDonwloader_directory}PatreonDownloader.App \
    --url https://www.patreon.com/$creator/posts \
    --download-directory ${content_directory}$creator/
```

for remote browser (as an alternative) I'm using:

```
chromium --remote-debugging-port=9222 > /dev/null 2>&1 &
${PatreonDonwloader_directory}PatreonDownloader.App \
    --remote-browser-address ws://127.0.0.1:9222 \
    --url https://www.patreon.com/$creator/posts \
    --download-directory ${content_directory}$creator/
```

PatreonDownloader version: 0.10.1.2
Chromium version: 100.0.4896.60
os: ubuntu 20.04.3
de: cinnammon 4.4.8

**Comment by shinji257** [comment]
For the first one I hit that today.  I went and logged out of a session in a different browser (that had logged in fine before) then logged in again from there.  After that Patreon Downloader was able to login normally with the provided browser.  Not sure what is going on with the second one though.

**Comment by AlexCSDev** [comment]
0.10.2 is not really tested to properly work with remote browser and this feature will probably be removed unless someone wants to test and make it work with captcha automation code.

Please try this test build:
https://mega.nz/file/211WVIoL#CSkmHdALPMVluaxUW4oHlaPLG8l_Kakj-83MGI5Srdo

**Make sure to extract it to separate folder and make sure you are not running any kind of VPN or other software/hardware which can alter the way requests are sent from your computer**

**Comment by AlexCSDev** [comment]
Closed as I have not received further feedback
