### ISSUE TITLE
Browser for Capture wont open

### ISSUE THREAD

**Issue by ElyFura** [AlexCSDev/PatreonDownloader#120]
After Login and start Connecting it tries to open the Browser to Solche the Capture but the Browser doesnt appear

`2022-04-20 19:12:12.9848 INFO Preparing to download...
2022-04-20 19:12:13.5265 WARN Captcha has been triggered, the browser window will be opened now. Please solve the captcha there.
2022-04-20 19:12:13.5265 DEBUG Initializing PuppeteerEngine with parameters , True
2022-04-20 19:12:13.5391 DEBUG Calling captcha check
2022-04-20 19:12:13.5391 DEBUG Retrieving browser
2022-04-20 19:12:13.5391 DEBUG Downloading browser
2022-04-20 19:12:13.5391 DEBUG Launching browser
2022-04-20 19:12:13.7119 DEBUG Opening new page
2022-04-20 19:12:13.9261 DEBUG Creating IWebBrowser
2022-04-20 19:12:14.0134 DEBUG Checking if captcha is returned
2022-04-20 19:12:17.9093 DEBUG Captcha was not returned, done
2022-04-20 19:12:17.9140 DEBUG Retrieving browser
2022-04-20 19:12:17.9140 DEBUG Retrieving cookies
2022-04-20 19:12:20.2664 DEBUG Adding cookie: datadome
2022-04-20 19:12:20.2664 DEBUG Adding cookie: amplitude_idpatreon.com
2022-04-20 19:12:20.2664 DEBUG Adding cookie: _dd_s
2022-04-20 19:12:20.2664 DEBUG Adding cookie: __cf_bm
2022-04-20 19:12:20.2750 DEBUG Adding cookie: patreon_locale_code
2022-04-20 19:12:20.2750 DEBUG Adding cookie: _fbp
2022-04-20 19:12:20.2750 DEBUG Adding cookie: _gid
2022-04-20 19:12:20.2750 DEBUG Adding cookie: G_ENABLED_IDPS
2022-04-20 19:12:20.2750 DEBUG Adding cookie: _gat
2022-04-20 19:12:20.2910 DEBUG Adding cookie: _scid
2022-04-20 19:12:20.2910 DEBUG Adding cookie: patreon_location_country_code
2022-04-20 19:12:20.2910 DEBUG Adding cookie: _rdt_uuid
2022-04-20 19:12:20.3040 DEBUG Adding cookie: _ga
2022-04-20 19:12:20.3040 DEBUG Adding cookie: _gcl_au
2022-04-20 19:12:20.3040 DEBUG Adding cookie: patreon_device_id
2022-04-20 19:12:20.3040 DEBUG Adding cookie: __ssid
2022-04-20 19:12:20.3231 DEBUG Adding cookie: _ALGOLIA
2022-04-20 19:12:20.3231 DEBUG Adding cookie: session_id
2022-04-20 19:12:20.3231 DEBUG Disposing puppeteer engine
2022-04-20 19:12:20.3967 WARN Captcha has been triggered, the browser window will be opened now. Please solve the captcha there.
2022-04-20 19:12:20.3983 DEBUG Initializing PuppeteerEngine with parameters , True
2022-04-20 19:12:20.3983 DEBUG Found 2 chrome processes (not sure which one yet)
2022-04-20 19:12:21.2086 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve campaign id: Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen.
 ---> System.ComponentModel.Win32Exception (299): Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.<>c.<KillChromeIfRunning>b__10_0(Process x) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 75
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.KillChromeIfRunning() in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 74
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.Initialize(Uri remoteBrowserAddress, Boolean headless) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 63
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine..ctor(Boolean headless) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 48
   at PatreonDownloader.PuppeteerEngine.PuppeteerCaptchaSolver..ctor() in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCaptchaSolver.cs:line 24
   at PatreonDownloader.Implementation.PatreonWebDownloader.SolveCaptchaAndUpdateCookies(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 82
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 63
   at PatreonDownloader.Implementation.PatreonWebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonWebDownloader.cs:line 66
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 36
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 49
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 24
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 176
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69`

Windows 11

**Comment by AlexCSDev** [comment]
> Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen.

This is some kind of an issue with your computer and/or network connection. Please look at #115 for possible solutions.
