### ISSUE TITLE
Campaign id cannot be less than 1 ?

### ISSUE THREAD

**Issue by rebeltaz** [AlexCSDev/PatreonDownloader#126]
I don't think this is related to the "cannot retrieve campaign ID" issue, so I'm starting a new topic.  If It is, I apologize. I am trying to run the latest PatreonDownloader under Ubuntu 1804 LTS using this as the command line:

 ./PatreonDownloader.App --url https://onlyfans.com/username --download-directory ~/videos/ --descriptions --embeds --campaign-images --json

I am getting this error:

2022-05-23 19:59:38.2207 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')
 ---> System.ArgumentOutOfRangeException: Campaign id cannot be less than 1 (Parameter 'campaignId')
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 58
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 75
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 26
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 176
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

What does this mean?

**Comment by AlexCSDev** [comment]
Why are you trying to download onlyfans with application which is designed for patreon.com?

Closed.

**Comment by rebeltaz** [comment]
Because I'm an idiot. I'm sorry about that.
