### ISSUE TITLE
latest version still getting the infinite verification

### ISSUE THREAD

**Issue by gradyhouston** [AlexCSDev/PatreonDownloader#128]
Using the latest version `0.10.3.0`, I'm still getting the infinite verification loop in Chromium. No matter how many times I "complete" the slider, it just refreshes back to the bot verification. Below is the error when I eventually have to close the Chromium browser. I've searched current/past issues and found the post where this was fixed in the latest version, but something is still blocking the verification. I also tried an older version, `0.9.4.2` because others said this version worked, but it also failed to pass the bot verification.

```2022-06-03 01:06:40.6448 INFO Retrieving cookies...
2022-06-03 01:06:59.1670 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at PatreonDownloader.App.Program.InitializeSettings(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 166
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 142
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69```

**Comment by AlexCSDev** [comment]
Unless a lot of other people report it, I think this is an issue with patreon's datadome protection having more strict rules for your ISP. If that is the case I can do nothing about that other than recommend you to use VPN.

Try using [Cloudflare WARP](https://1.1.1.1/). Make sure "1.1.1.1 with WARP" mode is enabled. If that doesn't work try using fully featured VPN.

**Comment by fueledbyboredom** [comment]
Running into the same issue here.. I've tried with antivirus and firewall both on and totally disabled, over a VPN connection and without it.

```
2022-06-03 13:29:06.0659 INFO Retrieving cookies...
2022-06-03 13:30:04.5508 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at PatreonDownloader.App.Program.InitializeSettings(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 166
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 142
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69
```

**Comment by AlexCSDev** [comment]
We are currently trying to figure out other connection-related problem in #125, if we'll be able to figure out what is wrong there it might also fix this issue.

**Comment by AlexCSDev** [comment]
Seems like this cannot be fixed. Wait for the new version to be released and then just wait a day or two and it should work fine. https://github.com/AlexCSDev/PatreonDownloader/issues/125#issuecomment-1171281572

**Comment by AlexCSDev** [comment]
Actually I might have fixed it. Please continue the discussion of this issue in: https://github.com/AlexCSDev/PatreonDownloader/issues/125
