### ISSUE TITLE
Inner Exception: The service drive has thrown an exception.

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#143]
`ERROR Failed to download https://drive.google.com/drive/folders/###?usp=sharing: Error while downloading https://drive.google.com/drive/folders/###?usp=sharing: Unable to download https://drive.google.com/drive/folders/###?usp=sharing. Inner Exception: The service drive has thrown an exception.
HttpStatusCode is NotFound.
Google.Apis.Requests.RequestError
File not found: ### [404]
Errors [
        Message[File not found: ###] Location[fileId - parameter] Reason[notFound] Domain[global]
]

Google.GoogleApiException: The service drive has thrown an exception. HttpStatusCode is NotFound. File not found: ###
   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at UniversalDownloaderPlatform.GoogleDriveDownloader.GoogleDriveEngine.Download(String id, String path, Boolean overwrite)
   at UniversalDownloaderPlatform.GoogleDriveDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory)`

I seem to receive this message regardless of the drive file in question.

**Comment by AlexCSDev** [comment]
I can't reproduce this issue. Please provide a link which throws an error in the app, but works in the browser. The link can be posted either here or sent to alexcsdev@protonmail.com
