### ISSUE TITLE
FATAL System.ArgumentNullException: Value cannot be null. (Parameter 'html')

### ISSUE THREAD

**Issue by aksskl** [AlexCSDev/PatreonDownloader#145]
I've come across this error within the last twelve hours while crawling. Has anyone else experienced this? It seems random which creators are affected. 

`FATAL Fatal error, application will be closed: System.ArgumentNullException: Value cannot be null. (Parameter 'html')
   at HtmlAgilityPack.HtmlDocument.LoadHtml(String html)
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.ExtractSupportedUrls(String htmlContents)
   at UniversalDownloaderPlatform.Engine.PluginManager.ExtractSupportedUrls(String htmlContents) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\PluginManager.cs:line 112
   at PatreonDownloader.Implementation.PatreonPageCrawler.ParsePage(String json, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 217
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 90
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69`

**Comment by emerladCoder** [comment]
I had the same issue and was able to fix by just ensuring that value isn't null.

In PatreonDownloader.Implementation\PatreonPageCrawler.cs I just test if the Content is null and if it is pass an empty string instead of null value. That fixed the issue for me.

`//External urls via plugins (including direct via default plugin)
List<string> pluginUrls = await _pluginManager.ExtractSupportedUrls(jsonEntry.Attributes.Content != null ? jsonEntry.Attributes.Content : "");`

**Comment by aksskl** [comment]
That has also fixed the issue for me. Thanks

**Comment by DarkRoku12** [comment]
Can this be fixed in the binary provided?

**Comment by AlexCSDev** [comment]
Fixed in 0.10.5.0
