### ISSUE TITLE
Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by CmdrShepardsPie** [AlexCSDev/PatreonDownloader#149]
2022-11-07 11:41:49.2575 INFO Crawling...
2022-11-07 11:41:49.7323 FATAL Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.Implementation.PatreonPageCrawler.ParsePage(String json, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 350
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 90
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

**Comment by AlexCSDev** [comment]
Make sure you are running latest version. If you do then run the application with `--json --log-level Trace --log-save` parameters and send logs and resulting json files to alexcsdev@protonmail.com

**Comment by AlexCSDev** [comment]
No feedback, closed
