### ISSUE TITLE
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

### ISSUE THREAD

**Issue by CmdrShepardsPie** [AlexCSDev/PatreonDownloader#150]
2022-11-07 11:41:28.8802 INFO Downloaded 265/267: https://c10.patreonusercontent.com/4/patreon-media/p/post/21634081/e829aab92e9c434b87d36ca92254c32a/eyJwIjoxfQ%3D%3D/1.png?token-time=1669075200&token-hash=sx6KZN6LRQyZ_fFeE4Ap6ReWaKWzIuMO_Fw-C_IIipU%3D
2022-11-07 11:41:29.0468 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Engine.Exceptions.UniversalDownloaderPlatformException: Error while downloading https://c10.patreonusercontent.com/4/patreon-media/p/post/68057276/2203fa476ed64833abcd77c189e0e290/eyJhIjoxLCJwIjoxfQ%3D%3D/1.jpg?token-time=1667952000&token-hash=zb8n4fom9Ty_ZezN8G82SMFaiNUVQz4SdOTF4pbFcHw%3D: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at PatreonDownloader.Implementation.PatreonCrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl udpCrawledUrl, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawledUrlProcessor.cs:line 173
   at UniversalDownloaderPlatform.Engine.DownloadManager.<>c__DisplayClass8_1.<<Download>b__0>d.MoveNext() in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\DownloadManager.cs:line 72
   --- End of inner exception stack trace ---
   at UniversalDownloaderPlatform.Engine.DownloadManager.<>c__DisplayClass8_1.<<Download>b__0>d.MoveNext() in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\DownloadManager.cs:line 101
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.Engine.DownloadManager.Download(List`1 crawledUrls, String downloadDirectory, CancellationToken cancellationToken) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\DownloadManager.cs:line 114
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 204
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

**Comment by AlexCSDev** [comment]
Stop spamming the issues page, thank you.
