### ISSUE TITLE
Does not work  ,  tried last 2 versions 

### ISSUE THREAD

**Issue by joinstuff** [AlexCSDev/PatreonDownloader#151]
Does not work , I got the following errors :

2022-11-14 23:13:10.7494 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')
 ---> System.ArgumentOutOfRangeException: Campaign id cannot be less than 1 (Parameter 'campaignId')
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 58
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 75
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 26
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 176
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69

**Comment by Saurfon** [comment]
Make sure the Patreon link that you are using is correct. I was having the same issue, but then after I tried actually going to the URL I was giving this program I realized the creator's channel name in the URL is different from the one that shows up on my memberships page.

**Comment by joinstuff** [comment]
It managed to crawl  now  but cannot download Vimeo videos....
2022-11-16 00:05:38.3525 ERROR Failed to download https://vimeo.com/683208587/46172ce01a: Error while downloading https://vimeo.com/683208587/46172ce01a: [63212095] Unable to retrieve name for external entry of type ExternalUrl: https://vimeo.com/683208587/46172ce01a

All videos on Patreon are available.

**Comment by AlexCSDev** [comment]
Vimeo is not supported
