### ISSUE TITLE
CG.Web.MegaApiClient.ApiException: API response: ToManyRequestsForThisResource

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#154]
Looks like Mega links to banned accounts report the wrong error? "This link is unavailable as the user’s account has been closed for gross violation of MEGA’s Terms of Service". But error information says too many requests for this resource. 
Google drive still suffers from #143 

```
2022-12-25 13:31:20.0222 ERROR Error while downloading https://mega.nz/folder/###: Unable to download https://mega.nz/folder/###: CG.Web.MegaApiClient.ApiException: API response: ToManyRequestsForThisResource
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodeFromLink(Uri uri)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.MegaDownloader.MegaDownloader.DownloadUrlAsync(ICrawledUrl crawledUrl, String downloadPath, Boolean overwriteFiles)
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory). Inner Exception: CG.Web.MegaApiClient.ApiException: API response: ToManyRequestsForThisResource
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodeFromLink(Uri uri)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.MegaDownloader.MegaDownloader.DownloadUrlAsync(ICrawledUrl crawledUrl, String downloadPath, Boolean overwriteFiles)
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory)
2022-12-25 13:31:20.0222 ERROR Failed to download https://mega.nz/folder/###: Error while downloading https://mega.nz/folder/###: Unable to download https://mega.nz/folder/###: CG.Web.MegaApiClient.ApiException: API response: ToManyRequestsForThisResource
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodeFromLink(Uri uri)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.MegaDownloader.MegaDownloader.DownloadUrlAsync(ICrawledUrl crawledUrl, String downloadPath, Boolean overwriteFiles)
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory). Inner Exception: CG.Web.MegaApiClient.ApiException: API response: ToManyRequestsForThisResource
   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)
   at CG.Web.MegaApiClient.MegaApiClient.GetNodeFromLink(Uri uri)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.MegaDownloader.MegaDownloader.DownloadUrlAsync(ICrawledUrl crawledUrl, String downloadPath, Boolean overwriteFiles)
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory)
```

**Comment by AlexCSDev** [comment]
Nothing I can do about that. This error is reported by the external library
