### ISSUE TITLE
Windows Issue if Parameter --use-sub-directories --sub-directory-pattern %PostTitle% is used

### ISSUE THREAD

**Issue by apg1980** [AlexCSDev/PatreonDownloader#156]
Hello,

if you are using --use-sub-directories --sub-directory-pattern %PostTitle% and the PostTitle is longer than 255 Letters the whole download breaks with an exception.

Can you please add an Parameter to limit the max Directory Name Size?

Thanks a lot

i got a error like this:
`2023-01-09 19:00:14.2241 FATAL Fatal error, application will be closed: System.IO.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\TEST\In dieser Videoserie erzähle ich Euch eine Zusammenfassung meiner Biografie, meiner Lebensgeschichte und meiner musikalischer Erfahrung. Dies ist ein sehr persönlicher Einblick in mein Leben und beim beenden der Serie solltet Ihr ein klares Bild meiner Person haben, wie auch einen Ausblick auf den Inhalt meines biografischen Lehrbuches an dem ich seit einiger Zeit arbeite'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at PatreonDownloader.Implementation.PatreonPageCrawler.ParsePage(String json, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 159
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 90
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69`

**Comment by AlexCSDev** [comment]
Implemented in latest version
