### ISSUE TITLE
FATAL Fatal error, application will be closed:

### ISSUE THREAD

**Issue by railannad** [AlexCSDev/PatreonDownloader#17]
Hello , I met an error when I used it.
COMMAND: PatreonDownloader.App.exe --creator https://www.patreon.com/u_u_ASMR
OUTPUT:
2020-10-24 16:31:07.4316 INFO Retrieving cookies...
2020-10-24 16:31:52.3954 FATAL Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 49
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 118
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59
![image](https://user-images.githubusercontent.com/36919867/97077478-a5b31280-1616-11eb-8e83-e0c337031ace.png)

Thank you in advance

**Comment by AlexCSDev** [comment]
First of all your creator url is not correct. It should follow the following format: https://www.patreon.com/#creator_name_here#/posts.

But that's not the problem. It looks like the browser could not be started. Please post the most recent log file from the "logs" directory.

**Comment by railannad** [comment]
> First of all your creator url is not correct. It should follow the following format: https://www.patreon.com/#creator_name_here#/posts.
> 
> But that's not the problem. It looks like the browser could not be started. Please post the most recent log file from the "logs" directory.
Thank you for replying. Here are logs:

2020-10-24 16:31:07.3455 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Found 27 chrome processes (not sure which one yet)
2020-10-24 16:31:07.4316 INFO [PatreonDownloader.App.Program] Retrieving cookies...
2020-10-24 16:31:07.4640 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Calling login check
2020-10-24 16:31:07.4784 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Retrieving browser
2020-10-24 16:31:07.4863 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
2020-10-24 16:31:50.6138 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
2020-10-24 16:31:52.2779 FATAL [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Browser communication error. Exception: PuppeteerSharp.ChromiumProcessException: Failed to create connection
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultWebSocket(Uri url, IConnectionOptions options, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultTransport(Uri url, IConnectionOptions connectionOptions, CancellationToken cancellationToken)
   at PuppeteerSharp.Connection.Create(String url, IConnectionOptions connectionOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.GetBrowser() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 92
2020-10-24 16:31:52.3954 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 49
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 118
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59
2020-10-24 16:35:03.1810 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Found 24 chrome processes (not sure which one yet)
2020-10-24 16:35:03.2213 INFO [PatreonDownloader.App.Program] Retrieving cookies...
2020-10-24 16:35:03.2512 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Calling login check
2020-10-24 16:35:03.2645 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Retrieving browser
2020-10-24 16:35:03.2645 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
2020-10-24 16:35:03.2866 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
2020-10-24 16:35:05.6824 FATAL [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Browser communication error. Exception: PuppeteerSharp.ChromiumProcessException: Failed to create connection
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultWebSocket(Uri url, IConnectionOptions options, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultTransport(Uri url, IConnectionOptions connectionOptions, CancellationToken cancellationToken)
   at PuppeteerSharp.Connection.Create(String url, IConnectionOptions connectionOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.GetBrowser() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 92
2020-10-24 16:35:05.6919 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 49
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 118
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59
2020-10-24 16:42:32.2365 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Found 24 chrome processes (not sure which one yet)
2020-10-24 16:42:32.3092 INFO [PatreonDownloader.App.Program] Retrieving cookies...
2020-10-24 16:42:32.3404 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Calling login check
2020-10-24 16:42:32.3541 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Retrieving browser
2020-10-24 16:42:32.3615 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
2020-10-24 16:42:32.3772 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
2020-10-24 16:42:33.7362 FATAL [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Browser communication error. Exception: PuppeteerSharp.ChromiumProcessException: Failed to create connection
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultWebSocket(Uri url, IConnectionOptions options, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultTransport(Uri url, IConnectionOptions connectionOptions, CancellationToken cancellationToken)
   at PuppeteerSharp.Connection.Create(String url, IConnectionOptions connectionOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.GetBrowser() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 92
2020-10-24 16:42:33.7362 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 49
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 118
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59

**Comment by AlexCSDev** [comment]
Yep, looks like there are some problems with accessing embedded browser.

Please try running this test build: https://mega.nz/file/qtcwQLpb#Wx3FoHAgIPzjFKc3BPCS073sU_xAeZzxuXaNM-OQ1p0

Please note that this is only a test build and it comes without google drive plugin. I will make a proper release if this solves your issue.

**Comment by railannad** [comment]
> Yep, looks like there are some problems with access to the embedded browser.
> 
> Please try running this test build: https://mega.nz/file/qtcwQLpb#Wx3FoHAgIPzjFKc3BPCS073sU_xAeZzxuXaNM-OQ1p0
> 
> Please note that this build comes without google drive plugin. I will make a proper release if this solves your issue.

Thank you for updating and I am sorry for that it still can not work.
![image](https://user-images.githubusercontent.com/36919867/97096912-b8285d00-16a5-11eb-9267-2bb2398ce4b6.png)

Here are logs:
2020-10-25 09:32:56.1199 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Found 24 chrome processes (not sure which one yet)
2020-10-25 09:32:56.1663 INFO [PatreonDownloader.App.Program] Retrieving cookies...
2020-10-25 09:32:56.2063 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Calling login check
2020-10-25 09:32:56.2181 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever] Retrieving browser
2020-10-25 09:32:56.2181 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
2020-10-25 09:33:26.7836 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
2020-10-25 09:33:27.2929 FATAL [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Browser communication error. Exception: PuppeteerSharp.ProcessException: Failed to create connection
 ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultWebSocket(Uri url, IConnectionOptions options, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultTransport(Uri url, IConnectionOptions connectionOptions, CancellationToken cancellationToken)
   at PuppeteerSharp.Connection.Create(String url, IConnectionOptions connectionOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options, Product product)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options, Product product)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options, Product product)
   at PatreonDownloader.PuppeteerEngine.PuppeteerEngine.GetBrowser() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerEngine.cs:line 92
2020-10-25 09:33:27.3493 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.Login() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 49
   at PatreonDownloader.PuppeteerEngine.PuppeteerCookieRetriever.RetrieveCookies() in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PuppeteerCookieRetriever.cs:line 93
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 118
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59

**Comment by railannad** [comment]
I wonder if  I need close my browser when I excuting the command.  
And I live in a magical country so I have to access to patreon with proxy.
I pasted `set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890` to CMD and that may be the cause of the error

**Comment by AlexCSDev** [comment]
PatreonDownloader should not conflict with any other chromium-based browsers.

Try disabling any applications/settings which may affect network connectivity in any way (vpn, proxy, firewall, etc). I'm afraid that's the only thing I can think of. 

Another thing you can use is --no-headless parameter which should show browser window which in turn you can use to figure out what might be wrong.

I am closing this issue as wontfix since it doesn't appear that this problem is related to PatreonDownloader.

**Comment by railannad** [comment]
I closed proxy and the PatreonDownloader opened the chrome successfully.  I logged in and  it said "Unable to create download directory"  



2020-10-26 18:02:26.3810 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Downloading browser
2020-10-26 18:02:26.3810 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Launching browser
2020-10-26 18:02:26.6164 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Opening new page
2020-10-26 18:02:26.7242 DEBUG [PatreonDownloader.PuppeteerEngine.PuppeteerEngine] Creating IWebBrowser
2020-10-26 18:02:28.4740 FATAL [PatreonDownloader.Engine.PatreonDownloader] Unable to create download directory: System.IO.IOException: 文件名、目录名或卷标语法不正确。 : 'D:\github\patreon_downloader\download\https:\www.patreon.com\u_u_asmr\posts'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 138
2020-10-26 18:02:28.4999 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.PatreonDownloaderException: Unable to create download directory
 ---> System.IO.IOException: 文件名、目录名或卷标语法不正确。 : 'D:\github\patreon_downloader\download\https:\www.patreon.com\u_u_asmr\posts'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 138
   --- End of inner exception stack trace ---
   at PatreonDownloader.Engine.PatreonDownloader.Download(String creatorName, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 144
   at PatreonDownloader.App.Program.RunPatreonDownloader(String creatorName, Boolean headlessBrowser, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 137
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 59

**Comment by AlexCSDev** [comment]
Sorry, that was my mistake, the correct download command for you will be: PatreonDownloader.App.exe --creator u_u_ASMR

**Comment by railannad** [comment]
> Sorry, that was my mistake, the correct download command for you will be: PatreonDownloader.App.exe --creator u_u_ASMR

Yes,I used `--creator u_u_ASMR` and it worked successfully. I am sorry for that I did not read README carefully
PatreonDownloader is a convenient script , thank you
