### ISSUE TITLE
Cannot find subscription

### ISSUE THREAD

**Issue by casualkot** [AlexCSDev/PatreonDownloader#173]
Cannot find subscription.
Model: Anabel054
Maybe because she has many plans...

**Comment by AlexCSDev** [comment]
You need to provide more information like logs if you want to get help.

**Comment by casualkot** [comment]
sorry, wrong thread :)
for this:
...
DEBUG [UniversalDownloaderPlatform.PuppeteerEngine.PuppeteerEngine] Creating IWebBrowser
DEBUG [UniversalDownloaderPlatform.PuppeteerEngine.PuppeteerCookieRetriever] Checking login status
FATAL [UniversalDownloaderPlatform.PuppeteerEngine.PuppeteerCookieRetriever] Login error: net::ERR_CONNECTION_RESET at https://www.patreon.com/api/current_user at https://www.patreon.com/api/current_user
FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in e:\Patreon\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 138
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in e:\Patreon\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in e:\Patreon\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68

**Comment by AlexCSDev** [comment]
You are having connection issues to patreon. Check that your isp is not blocking your connection to patreon. If you are using VPN make sure it is setup to send either all application traffic trough it or add PatreonDownloader there. If you are using proxy - use `--proxy-server-address` parameter to set proxy server connection details.
