### ISSUE TITLE
datadome cookie not found

### ISSUE THREAD

**Issue by Wolfeman0101** [AlexCSDev/PatreonDownloader#174]
`.\PatreonDownloader.App.exe --url https://www.patreon.com/user/posts?u=XXXXXXX --download-directory .\Ally --descriptions --embeds --campaign-images --json
2023-03-30 01:30:51.3611 INFO Preparing to download...
2023-03-30 01:30:51.3953 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.CookieValidationException: datadome cookie not found
   at PatreonDownloader.Implementation.PatreonCookieValidator.ValidateCookies(CookieContainer cookieContainer) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCookieValidator.cs:line 38
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 181
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68`

**Comment by JajaKuroneko** [comment]
Hi! I experienced the same error message, but was able to circumvent (for now) by removing the check for that particular cookie from the referenced file. Seems to be working fine so far. Hopefully that helps at least a bit. (Sorry. Not a code guru.)

**Comment by AlexCSDev** [comment]
I will look into this within a few days

**Comment by jtayl711** [comment]
> Hi! I experienced the same error message, but was able to circumvent (for now) by removing the check for that particular cookie from the referenced file. Seems to be working fine so far. Hopefully that helps at least a bit. (Sorry. Not a code guru.)

Can you explain how you did this?  I've been receiving the same error.

**Comment by JajaKuroneko** [comment]
> > Hi! I experienced the same error message, but was able to circumvent (for now) by removing the check for that particular cookie from the referenced file. Seems to be working fine so far. Hopefully that helps at least a bit. (Sorry. Not a code guru.)
> 
> Can you explain how you did this? I've been receiving the same error.

I opened "PatreonCookieValidator.cs" in Notepad and saw what appears to be an "if-then" clause starting at line 37 (Turn off text wrapping if you're using Notepad, too.) that triggers this error message if this specific cookie is not found.
```
if (cookies["datadome"] == null)
                throw new CookieValidationException("datadome cookie not found");
```
I just deleted these two lines and saved the file before running like normal. I'm guessing that Patreon stopped using this cookie in the last month or so?

Hopefully that is more helpful. I'm, like, brand new here.

**Comment by AlexCSDev** [comment]
I have disabled the check for datadome cookie in latest release. I'm not entirely sure what is going on because I'm still getting this cookie on my side. I guess they might be doing some kind of A/B testing on their side.
