### ISSUE TITLE
Getting Fatal error System.NullReferenceException:Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Spyridion** [AlexCSDev/PatreonDownloader#183]
I tried against two different creators and I'm getting the same error. I'm not sure where the error is coming from. Here's the text from the error:
`2023-05-14 21:04:44.2044 FATAL Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalDownloaderPlatform.MegaDownloader.Plugin.BeforeStart(IUniversalDownloaderPlatformSettings settings)
   at UniversalDownloaderPlatform.Engine.PluginManager.BeforeStart(IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\PluginManager.cs:line 77
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 177
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68`

**Comment by xduQuzhen** [comment]
I meet the same problem and solved it.
Your region has blocked the mega service, so you have to add the following command before in cmd before starting download.
You should change port which is your proxy sofrware setting.(7890->yours port)
set http_proxy=http://127.0.0.1:7890   
set https_proxy=http://127.0.0.1:7890

curl https://www.google.com

if curl command return html,it works.

**Comment by Spyridion** [comment]
Interesting. It works once I remove my mega credentials. Unfortunately, I'm on windows so I don't have a proxy atm.
