### ISSUE TITLE
Cookies issue

### ISSUE THREAD

**Issue by pmader60** [AlexCSDev/PatreonDownloader#192]
2023-08-13 16:20:50.5985 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.CookieValidationException: datadome cookie not found
   at PatreonDownloader.Implementation.PatreonCookieValidator.ValidateCookies(CookieContainer cookieContainer) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCookieValidator.cs:line 38
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 181
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68

**Comment by AlexCSDev** [comment]
Install latest version
