### ISSUE TITLE
Browser doesnt open: Couldn't mmap icu data file

### ISSUE THREAD

**Issue by My1** [AlexCSDev/PatreonDownloader#193]
Kubuntu 22.04, I do have both Chrome and Chromium installed

Trace Log:
```
2023-08-27 09:32:38.4629 DEBUG Initializing UniversalDownloader...
2023-08-27 09:32:38.4765 DEBUG Initializing ninject kernel
2023-08-27 09:32:38.4973 DEBUG Loading custom ninject module
2023-08-27 09:32:38.5009 DEBUG Loading ICrawlTargetInfoRetriever
2023-08-27 09:32:38.5336 DEBUG Configuring IPageCrawler
2023-08-27 09:32:38.5586 DEBUG New plugin found: UniversalDownloaderPlatform.GoogleDriveDownloader.dll
2023-08-27 09:32:38.5586 FATAL !!!![GOOGLE DRIVE]: gd_credentials.json not found, google drive files will not be downloaded! Refer to documentation for additional information. !!!!
2023-08-27 09:32:38.5651 INFO Loaded plugin: Google Drive Downloader
2023-08-27 09:32:38.5651 DEBUG New plugin found: UniversalDownloaderPlatform.MegaDownloader.dll
2023-08-27 09:32:38.5674 WARN !!!![MEGA]: mega_credentials.json not found, mega downloading will be limited! Refer to documentation for additional information. !!!!
2023-08-27 09:32:39.0099 INFO Loaded plugin: Mega.nz Downloader
2023-08-27 09:32:39.0116 DEBUG Initializing plugin manager
2023-08-27 09:32:39.0116 DEBUG Initializing download manager
2023-08-27 09:32:39.0181 DEBUG KemonoCrawledUrlProcessor initialized
2023-08-27 09:32:39.0193 DEBUG Initializing crawl results exporter
2023-08-27 09:32:39.0193 DEBUG Initializing url checker
2023-08-27 09:32:39.0193 DEBUG Initializing web downloader
2023-08-27 09:32:39.0193 DEBUG Initializing cookie retriever
2023-08-27 09:32:39.0193 DEBUG Initializing cookie validator
2023-08-27 09:32:39.0193 DEBUG Initializing crawled url processor
2023-08-27 09:32:39.0284 DEBUG Universal Downloader Platform settings: PatreonDownloaderSettings { CookieContainer = , UserAgent = , UrlBlackList = System.Collections.Generic.List`1[System.String], MaxDownloadRetries = 10, RetryMultiplier = 5, FileExistsAction = BackupIfDifferent, IsCheckRemoteFileSize = True, ProxyServerAddress = , DownloadDirectory = , SaveDescriptions = False, SaveEmbeds = False, SaveJson = False, SaveAvatarAndCover = False, IsUseSubDirectories = False, SubDirectoryPattern = [%PostId%] %PublishedAt% %PostTitle%, MaxSubdirectoryNameLength = 100, MaxFilenameLength = 100, FallbackToContentTypeFilenames = False, IsUseLegacyFilenaming = False, LoginPageAddress = https://www.patreon.com/login, LoginCheckAddress = https://www.patreon.com/api/current_user, CaptchaCookieRetrievalAddress = https://www.patreon.com/home, RemoteBrowserAddress = , IsHeadlessBrowser = True }
2023-08-27 09:32:39.0284 INFO Retrieving cookies...
2023-08-27 09:32:39.0284 DEBUG Initializing PuppeteerEngine with parameters , True
2023-08-27 09:32:39.0563 DEBUG Calling login check
2023-08-27 09:32:39.0636 DEBUG Retrieving browser
2023-08-27 09:32:39.0670 DEBUG Downloading browser
2023-08-27 09:32:39.0816 DEBUG Launching browser
2023-08-27 09:32:39.3322 FATAL Browser communication error. Exception: PuppeteerSharp.ProcessException: Failed to launch browser! [0827/093239.120671:ERROR:icu_util.cc(249)] Couldn't mmap icu data file
[0827/093239.120747:FATAL:content_main_delegate.cc(35)] Check failed: false. 
#0 0x55943479df49 base::debug::CollectStackTrace()
#1 0x559434707933 base::debug::StackTrace::StackTrace()
#2 0x55943471b500 logging::LogMessage::~LogMessage()
#3 0x55943471c04e logging::LogMessage::~LogMessage()
#4 0x55943112c345 content::ContentMainDelegate::TerminateForFatalInitializationError()
#5 0x5594342b788c content::ContentMainRunnerImpl::Initialize()
#6 0x5594342b5fa5 content::RunContentProcess()
#7 0x5594342b60cd content::ContentMain()
#8 0x559434314fd9 headless::HeadlessBrowserMain()
#9 0x559434314cf8 headless::HeadlessShellMain()
#10 0x559431128ae1 ChromeMain
#11 0x7f600a829d90 <unknown>
#12 0x7f600a829e40 __libc_start_main
#13 0x55943112892a _start


   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 68
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 91
   at UniversalDownloaderPlatform.PuppeteerEngine.PuppeteerEngine.StartLocalBrowser() in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.PuppeteerEngine\PuppeteerEngine.cs:line 146
2023-08-27 09:32:39.3402 FATAL Login error: Object reference not set to an instance of an object.
2023-08-27 09:32:39.3402 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 138
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68
```

**Comment by AlexCSDev** [comment]
This is a compatibility issue between underlying library and your OS, I'm afraid I can't provide support for that. You can try contacting Puppeteer/Puppeteer Sharp people directy.
