### ISSUE TITLE
Campaign id cannot be less than 1 Error

### ISSUE THREAD

**Issue by Skyl3lazer** [AlexCSDev/PatreonDownloader#196]
Getting the following error:

`2023-09-18 19:07:56.1702 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')
 ---> System.ArgumentOutOfRangeException: Campaign id cannot be less than 1 (Parameter 'campaignId')
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 58
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 75
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 26
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 183
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68`

**Comment by YakudzaKY** [comment]
+1 here...

**Comment by ToninoTarsi** [comment]
Same problem:
2023-09-19 10:43:24.9759 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')

**Comment by aksskl** [comment]
same here

**Comment by Skyl3lazer** [comment]
Created a PR that I believe fixes this issue 

https://github.com/AlexCSDev/PatreonDownloader/pull/197

**Comment by Skyl3lazer** [comment]
Also confirmed that it works when built from source code per build instructions with that PR implemented

**Comment by YakudzaKY** [comment]
> Also confirmed that it works when built from source code per build instructions with that PR implemented

a big thanks!

**Comment by ToninoTarsi** [comment]
> Created a PR that I believe fixes this issue
> 
> #197

With the PR it is working now.
Thanks

**Comment by icedstick** [comment]
Sorry i'm new to this. I have forked my own copy and modified the code as directed by Skyl3lazer. How do I compile everything in this fork into an executable to be able to run/use it?

**Comment by Skyl3lazer** [comment]
Read the build instructions as directed by the readme. It's another
document in the docs folder.

**Comment by icedstick** [comment]
I've spent a few hours trying to get this to work & keep failing in various different ways. Until AlexCSDev is able to return, could anyone please consider providing me with the amended "**PatreonDownloader.Implementation.pdb**" file or entire amended **net6.0-win-x64-release.zip**?

**Comment by angramainyuu** [comment]
I also tried compiling it according to the instructions but only got errors, I'm a complete noob mind you.
Would appreciate if someone could share it.

**Comment by angramainyuu** [comment]
> > I also tried compiling it according to the instructions but only got errors, I'm a complete noob mind you. Would appreciate if someone could share it.
> 
> Sure thing.
> 
> [debug-net6.0.zip](https://github.com/AlexCSDev/PatreonDownloader/files/12675516/debug-net6.0.zip)

Thank you!

**Comment by Mustached-Man** [comment]
> I've spent a few hours trying to get this to work & keep failing in various different ways. Until AlexCSDev is able to return, could anyone please consider providing me with the amended "**PatreonDownloader.Implementation.pdb**" file or entire amended **net6.0-win-x64-release.zip**?

https://github.com/AlexCSDev/PatreonDownloader/files/12675516/debug-net6.0.zip

**Comment by icedstick** [comment]
Thank you, lifesaver!

**Comment by JustFrederik** [comment]
for everyone who wants to compile it from source while it isnt fixed use this to clone the repo: `git clone https://github.com/Skyl3lazer/PatreonDownloader -b patch-1 --recursive`

**Comment by aa7326aa11** [comment]
Thank you

**Comment by jefflaunmg** [comment]
anyone can share a fixed build for linux, thx a lot!

**Comment by JustFrederik** [comment]
@jefflaunmg just build it yourself `build -c release`

**Comment by jdragoon** [comment]
What am I supposed to do with the debug-net6.0 file?

**Comment by JustFrederik** [comment]
@jdragoon nothing, download @Skyl3lazer fox and follow the instructions in the readme

**Comment by AlexCSDev** [comment]
Should be fixed in release 26/27, thanks to [Skyl3lazer](https://github.com/Skyl3lazer) for the fix!
