### ISSUE TITLE
FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')

### ISSUE THREAD

**Issue by CmdrShepardsPie** [AlexCSDev/PatreonDownloader#200]
I started getting this error a few days or weeks ago. I tried deleting everything to start fresh, including chrome folder so it required me to login again. 

Patreon $ .\PatreonDownloader.App.exe --url https://www.patreon.com/<...creator...>/posts --descriptions --embeds --campaign-images --json --log-level Trace
2023-09-22 11:25:26.2517 DEBUG Initializing UniversalDownloader...
2023-09-22 11:25:26.2517 DEBUG Initializing ninject kernel
2023-09-22 11:25:26.2691 DEBUG Loading custom ninject module
2023-09-22 11:25:26.2691 DEBUG Loading ICrawlTargetInfoRetriever
2023-09-22 11:25:26.2860 DEBUG Configuring IPageCrawler
2023-09-22 11:25:26.3025 DEBUG New plugin found: UniversalDownloaderPlatform.GoogleDriveDownloader.dll
2023-09-22 11:25:26.3831 DEBUG Token data saved to: GoogleDriveToken
2023-09-22 11:25:26.3831 INFO Loaded plugin: Google Drive Downloader
2023-09-22 11:25:26.3831 DEBUG New plugin found: UniversalDownloaderPlatform.MegaDownloader.dll
2023-09-22 11:25:27.4934 INFO Loaded plugin: Mega.nz Downloader
2023-09-22 11:25:27.4934 DEBUG Initializing plugin manager
2023-09-22 11:25:27.4934 DEBUG Initializing download manager
2023-09-22 11:25:27.4934 DEBUG KemonoCrawledUrlProcessor initialized
2023-09-22 11:25:27.4934 DEBUG Initializing crawl results exporter
2023-09-22 11:25:27.4934 DEBUG Initializing url checker
2023-09-22 11:25:27.4934 DEBUG Initializing web downloader
2023-09-22 11:25:27.4934 DEBUG Initializing cookie retriever
2023-09-22 11:25:27.4934 DEBUG Initializing cookie validator
2023-09-22 11:25:27.4992 DEBUG Initializing crawled url processor
2023-09-22 11:25:27.4992 DEBUG Universal Downloader Platform settings: PatreonDownloaderSettings { CookieContainer = , UserAgent = , UrlBlackList = System.Collections.Generic.List`1[System.String], MaxDownloadRetries = 10, RetryMultiplier = 5, FileExistsAction = BackupIfDifferent, IsCheckRemoteFileSize = True, ProxyServerAddress = , DownloadDirectory = , SaveDescriptions = True, SaveEmbeds = True, SaveJson = True, SaveAvatarAndCover = True, IsUseSubDirectories = False, SubDirectoryPattern = [%PostId%] %PublishedAt% %PostTitle%, MaxSubdirectoryNameLength = 100, MaxFilenameLength = 100, FallbackToContentTypeFilenames = False, IsUseLegacyFilenaming = False, LoginPageAddress = https://www.patreon.com/login, LoginCheckAddress = https://www.patreon.com/api/current_user, CaptchaCookieRetrievalAddress = https://www.patreon.com/home, RemoteBrowserAddress = , IsHeadlessBrowser = True }
2023-09-22 11:25:27.4992 INFO Retrieving cookies...
2023-09-22 11:25:27.4992 DEBUG Initializing PuppeteerEngine with parameters , True
2023-09-22 11:25:27.5165 DEBUG Calling login check
2023-09-22 11:25:27.5165 DEBUG Retrieving browser
2023-09-22 11:25:27.5165 DEBUG Downloading browser
2023-09-22 11:25:27.5165 DEBUG Launching browser
2023-09-22 11:25:27.6688 DEBUG Opening new page
2023-09-22 11:25:27.7653 DEBUG Creating IWebBrowser
2023-09-22 11:25:27.8243 DEBUG Checking login status
2023-09-22 11:25:28.1844 DEBUG We are logged in
2023-09-22 11:25:28.1888 DEBUG Retrieving browser
2023-09-22 11:25:28.1888 DEBUG Retrieving cookies
2023-09-22 11:25:28.4315 DEBUG Adding cookie: AWSALBTGCORS
2023-09-22 11:25:28.4315 DEBUG Adding cookie: patreon_device_id
2023-09-22 11:25:28.4315 DEBUG Adding cookie: __cf_bm
2023-09-22 11:25:28.4315 DEBUG Adding cookie: session_id
2023-09-22 11:25:28.4315 DEBUG Adding cookie: AWSALBTG
2023-09-22 11:25:28.4315 DEBUG Adding cookie: patreon_location_country_code
2023-09-22 11:25:28.4315 DEBUG Adding cookie: patreon_locale_code
2023-09-22 11:25:28.4315 DEBUG Adding cookie: a_csrf
2023-09-22 11:25:28.4368 DEBUG Disposing puppeteer engine
2023-09-22 11:25:28.4368 INFO Preparing to download...
2023-09-22 11:25:28.4368 WARN Datadome cookie was not found. Usually this is not an issue, but if you are experiencing any issues please make sure to report it via GitHub issues page.
2023-09-22 11:25:30.6211 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve crawl target info: Campaign id cannot be less than 1 (Parameter 'campaignId')
 ---> System.ArgumentOutOfRangeException: Campaign id cannot be less than 1 (Parameter 'campaignId')
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 58
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCrawlTargetInfo(Int64 campaignId) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 75
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 26
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 183
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68
Patreon $

**Comment by macereturn** [comment]
Same problem here !

**Comment by jdragoon** [comment]
Same error as #196 something changed and a pull request has been made. There's workaround advice in that thread and we should be getting an official fix soon.

**Comment by WinterSoldier1234** [comment]
Same

**Comment by apg1980** [comment]
Hello, would someone please be kind, to Compile a working windows executable and share the folder as a zip? thanks so much if this would be possible.

**Comment by Sinalco12** [comment]
> Hello, would someone please be kind, to Compile a working windows executable and share the folder as a zip? thanks so much if this would be possible.

Yeah a windows .exe would be pretty nice.

**Comment by dmo140230** [comment]
> > Hello, would someone please be kind, to Compile a working windows executable and share the folder as a zip? thanks so much if this would be possible.
> 
> Yeah a windows .exe would be pretty nice.

Here you go! I went ahead and compiled the fix from the other thread into a zip. It's 29MB and too big for a github comment so here's a link
https://www.mediafire.com/file/2argbjfhj4xbtqf/net6.0-win-x64-release-Skyl3lazer.zip/file

**Comment by apg1980** [comment]
thank you so much!!!!!!!!!!!!!!!!!!!

**Comment by AlexCSDev** [comment]
Current estimate for this issue to be addressed in the official build - some time next week.
