### ISSUE TITLE
ERROR Failed to download - Could not find part of the path, System Exception.

### ISSUE THREAD

**Issue by bahdahbadha** [AlexCSDev/PatreonDownloader#211]
Downloading fails because the path to the downloaded file is unable to be found? 
Below I write the entire error message for a single file (while also taking out possible personal data).

2023-12-17 18:07:12.9775 INFO Downloading...
2023-12-17 18:07:13.7679 ERROR Failed to download [LINK]: Error while downloading [LINK]: Unable to download from [LINK]: Could not find a part of the path 'C:\\net6.0-win-x64-release\download\[PATREON] \64669643_media_147675729_1.jpg.dwnldtmp'.. Inner Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\\net6.0-win-x64-release\download\[PATREON] \64669643_media_147675729_1.jpg.dwnldtmp'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadFileInternal(String url, String path, String refererUrl, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 218
2023-12-17 18:07:13.7679

Personally I found it weird that there was a space after the patreon name "...\[PATREON NAME] \658749..." in comparison to "...\[PATREON NAME]\658749..." 
, but I don't know much about coding so this might not matter at all.

**Comment by bahdahbadha** [comment]
I've figured out the issue! The creator I was trying to download from has a space at the end of their name which tries to make it into the path when downloading. This obviously means that the download path is unable to be found since well... Windows doesn't support spaces at the end of a path!

i.e. blah/blah /blah isn't supported as a valid path and when folders or files with spaces at the end are made they automatically turn into spaceless versions.
(so a/b /c attempts to make a/b / which turns into a/b/ which then means that a/b /c is unable to be found)

**Comment by TheSonic03** [comment]
Same issue

**Comment by J0SH1213** [comment]
just tried the above, the program just ignored the arguments, what worked was using \\?\  in command prompt to create a folder named the same as the one the program creates, then you have to use this to copy the data from and also to delete that folder once your done. for example, admin command prompt, do md "\\?\C:\Patreon Downloader\download\John Smith " to create the folder with a trailing space that the program is looking for, rd "\\?\C:\Patreon Downloader\download\John Smith " to delete the folder and lastly you need to use 7zip file manager, open it and in the adress bar paste \\?\C:\Patreon Downloader\download\John Smith and it should show all your files, then just select all and move em out of there. 

(fyi there is 2 slashes before the ?, not sure why gihub is consolidating it to just one...)
