### ISSUE TITLE
Brand new Cookie issue( I checked....?)

### ISSUE THREAD

**Issue by AriKhelvi** [AlexCSDev/PatreonDownloader#214]
So, I have been trying to download anything and this flow out:
C:\Users\AriKhelvi\Patreonthingy\PatreonDownloader\PatreonDownloader.App\bin\publish\net6.0-win-x64-release>PatreonDownloader.App.exe --url "https://www.patreon.com/posts/i-want-shorter-84883007"
2024-02-15 01:09:19.2438 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in C:\Users\AriKhelvi\Patreonthingy\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 138
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in C:\Users\AriKhelvi\Patreonthingy\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in C:\Users\AriKhelvi\Patreonthingy\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68

I have Opera, Edge and Chrome, all 3 have been logged in through login and password and I have build app through "## Building standalone executable via command line on all platforms" instructions. 

Any idea of how to fix it?
Can proxy used by me influensing it?

**Comment by cythrault** [comment]
I have the exact same issue. I've also tried to use a remote debugging session.
