### ISSUE TITLE
 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies

### ISSUE THREAD

**Issue by Ci9Quester** [AlexCSDev/PatreonDownloader#230]
I enter:
D:\Sofewarevault\Paterondownload\net6.0-win-x64-release>PatreonDownloader.App.exe --url https://www.patreon.com/shiun/posts

Then I get:
```
2024-08-09 22:41:53.7259 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 138
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 128
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 68

```
How can I fix this?
I downloaded the patches and fixes from other issues, but was told that only the latest version would work, and the rest would not.

**Comment by BedBug2479** [comment]
same happening to me

**Comment by lightSpeedBubble** [comment]
I just had a similar issue. My solution was to disable my VPN. Hopefully it's the same for you.
