### ISSUE TITLE
Unable to retrieve campaign id: Timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by dude22072** [AlexCSDev/PatreonDownloader#25]
Pastebin link of stacktrace here: [https://pastebin.com/ZDC6XaqJ](https://pastebin.com/ZDC6XaqJ)  
Username was changed to `<REDACTED>` just so it's not in the issue tracker forever, but it is just their username and doesn't have any symbols or anything.  
Using the latest available pre-compiled windows version of the tool. Downloading other creators seems to work fine but it's just this specific creator that seems to be getting a timeout error. Will send the name of the creator privately if it's needed to diagnose this.

**Comment by hugmouse** [comment]
Yep, same.

**OS info**

`Linux user 5.9.1-1-rt19-MANJARO #1 SMP PREEMPT_RT Sat Oct 24 16:27:39 UTC 2020 x86_64 GNU/Linux`

**Comment by AlexCSDev** [comment]
Do you see a "Checking your browser" page running in an endless loop on any of the browser tabs when you run app with --no-headless parameter?

**Comment by dude22072** [comment]
The spinner is remaining on the tab until the timeout error. I think the issue is the posts are very image heavy (It's a recipe patreon) and 30 seconds simply isn't enough time to load everything that gets shown on the main post page (I was scrolling down the page and images were still loading in). Perhaps a switch to specify timeout duration (something as simple as `--timeout 60000`) or simply having a `--no-timeout` option would fix my issue.

**Comment by AlexCSDev** [comment]
I'll see what I can do about this. Will be fixed in the next release which is planned for early january.

**Comment by AlexCSDev** [comment]
I have forced browser to not load images anymore. I think this will fix this problem.

You can either download and build commit 977aec6d8375e76303db7d72da805087d124df17 or wait for 0.9.4 to be released sometime this week.

**Comment by AlexCSDev** [comment]
Released in 0.9.4. Feel free to reopen this issue if problem persists.

**Comment by Nexus80** [comment]
I get the same error as before when trying to download from a patreon. Please can you fix a timeout for this issue?
I get the trouble after going through a poll and when it dies on the same place.

2021-01-08 20:30:02.4218 ERROR Verification for 149135: Unknown type for "included": poll
2021-01-08 20:30:34.5517 FATAL Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.DownloadException: Unable to download from https://www.patreon.com/api/posts?include=user%2Cattachments%2Ccampaign%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Caccess_rules.tier.null%2Cimages.null%2Caudio.null&fields%5Bpost%5D=change_visibility_at%2Ccomment_count%2Ccontent%2Ccurrent_user_can_delete%2Ccurrent_user_can_view%2Ccurrent_user_has_liked%2Cembed%2Cimage%2Cis_paid%2Clike_count%2Cmin_cents_pledged_to_view%2Cpost_file%2Cpost_metadata%2Cpublished_at%2Cpatron_count%2Cpatreon_url%2Cpost_type%2Cpledge_url%2Cthumbnail_url%2Cteaser_text%2Ctitle%2Cupgrade_url%2Curl%2Cwas_posted_by_campaign_owner&fields%5Buser%5D=image_url%2Cfull_name%2Curl&fields%5Bcampaign%5D=show_audio_post_download_links%2Cavatar_photo_url%2Cearnings_visibility%2Cis_nsfw%2Cis_monthly%2Cname%2Curl&fields%5Baccess_rule%5D=access_rule_type%2Camount_cents&fields%5Bmedia%5D=id%2Cimage_urls%2Cdownload_url%2Cmetadata%2Cfile_name&sort=-published_at&filter%5Bcampaign_id%5D=650363&filter%5Bis_draft%5D=false&filter%5Bcontains_exclusive_posts%5D=true&json-api-use-default-includes=false&json-api-version=1.0&page%5Bcursor%5D=C_gAIHZ3jTWm9Y-gNxkf_ubiQ4c: Timeout of 30000 ms exceeded
 ---> PuppeteerSharp.NavigationException: Timeout of 30000 ms exceeded
 ---> System.TimeoutException: Timeout of 30000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0()
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken)
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options)
   at PatreonDownloader.PuppeteerEngine.Wrappers.Browser.WebPage.GoToAsync(String url, Nullable`1 timeout, WaitUntilNavigation[] waitUntil) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\Wrappers\Browser\WebPage.cs:line 33
   at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\WebDownloader.cs:line 104
   --- End of inner exception stack trace ---
   at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\WebDownloader.cs:line 104
   at PatreonDownloader.Engine.Stages.Crawling.PageCrawler.Crawl(CampaignInfo campaignInfo, PatreonDownloaderSettings settings, String downloadDirectory) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\Stages\Crawling\PageCrawler.cs:line 71
   at PatreonDownloader.Engine.PatreonDownloader.Download(String url, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 240
   at PatreonDownloader.App.Program.RunPatreonDownloader(String url, Boolean headlessBrowser, Uri remoteBrowserAddress, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 161
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 74
