### ISSUE TITLE
Timeout due to patreon api responses slowing down considerably after reaching certain page/post count

### ISSUE THREAD

**Issue by Nexus80** [AlexCSDev/PatreonDownloader#30]
I get the same error as before this new version when trying to download from a patreon. Please can you fix a timeout for this issue?
I get the trouble after going through a poll and when it dies on the same place everytime.

2021-01-08 20:30:02.4218 ERROR Verification for 149135: Unknown type for "included": poll
2021-01-08 20:30:34.5517 FATAL Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.DownloadException: Unable to download from https://www.patreon.com/api/posts?include=user%2Cattachments%2Ccampaign%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Caccess_rules.tier.null%2Cimages.null%2Caudio.null&fields%5Bpost%5D=change_visibility_at%2Ccomment_count%2Ccontent%2Ccurrent_user_can_delete%2Ccurrent_user_can_view%2Ccurrent_user_has_liked%2Cembed%2Cimage%2Cis_paid%2Clike_count%2Cmin_cents_pledged_to_view%2Cpost_file%2Cpost_metadata%2Cpublished_at%2Cpatron_count%2Cpatreon_url%2Cpost_type%2Cpledge_url%2Cthumbnail_url%2Cteaser_text%2Ctitle%2Cupgrade_url%2Curl%2Cwas_posted_by_campaign_owner&fields%5Buser%5D=image_url%2Cfull_name%2Curl&fields%5Bcampaign%5D=show_audio_post_download_links%2Cavatar_photo_url%2Cearnings_visibility%2Cis_nsfw%2Cis_monthly%2Cname%2Curl&fields%5Baccess_rule%5D=access_rule_type%2Camount_cents&fields%5Bmedia%5D=id%2Cimage_urls%2Cdownload_url%2Cmetadata%2Cfile_name&sort=-published_at&filter%5Bcampaign_id%5D=650363&filter%5Bis_draft%5D=false&filter%5Bcontains_exclusive_posts%5D=true&json-api-use-default-includes=false&json-api-version=1.0&page%5Bcursor%5D=C_gAIHZ3jTWm9Y-gNxkf_ubiQ4c: Timeout of 30000 ms exceeded
---> PuppeteerSharp.NavigationException: Timeout of 30000 ms exceeded
---> System.TimeoutException: Timeout of 30000 ms exceeded
at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.b__0()
at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) --- End of inner exception stack trace --- at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) at PatreonDownloader.PuppeteerEngine.Wrappers.Browser.WebPage.GoToAsync(String url, Nullable1 timeout, WaitUntilNavigation[] waitUntil) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.PuppeteerEngine\Wrappers\Browser\WebPage.cs:line 33
at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\WebDownloader.cs:line 104
--- End of inner exception stack trace ---
at PatreonDownloader.Engine.WebDownloader.DownloadString(String url) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\WebDownloader.cs:line 104
at PatreonDownloader.Engine.Stages.Crawling.PageCrawler.Crawl(CampaignInfo campaignInfo, PatreonDownloaderSettings settings, String downloadDirectory) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\Stages\Crawling\PageCrawler.cs:line 71
at PatreonDownloader.Engine.PatreonDownloader.Download(String url, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 240
at PatreonDownloader.App.Program.RunPatreonDownloader(String url, Boolean headlessBrowser, Uri remoteBrowserAddress, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 161
at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 74

**Comment by AlexCSDev** [comment]
It appears that patreon api response time really slows down after reaching certain page (for this creator it happens on page 41-42).

I will need to add some timeout management code into page crawling process to fix this. Will look into it when I have some free time.

**Comment by AlexCSDev** [comment]
Interestingly enough this doesn't appear to happen on every creator who have a lot of pages. Removing this from 0.10.0 milestone for now since this needs further investigation

**Comment by NickUfer** [comment]
Why not just increase the timeout? Or make it adjustable?

**Comment by NickUfer** [comment]
For everyone else stumbling upon this here is a patch that just increases the timeout and fixes this:

```patch
diff --git a/PatreonDownloader.Engine/WebDownloader.cs b/PatreonDownloader.Engine/WebDownloader.cs
index 9b998d5..022af01 100644
--- a/PatreonDownloader.Engine/WebDownloader.cs
+++ b/PatreonDownloader.Engine/WebDownloader.cs
@@ -87,7 +87,7 @@ namespace PatreonDownloader.Engine
             {
                 IWebBrowser browser = await _puppeteerEngine.GetBrowser();
                 IWebPage page = await browser.NewPageAsync();
-                await page.GoToAsync(url);
+                await page.GoToAsync(url, 1000*180);
 
                 string content = await page.GetContentAsync();
                 await page.CloseAsync();
```

**Comment by AlexCSDev** [comment]
This should no longer happen in 0.10.0
