### ISSUE TITLE
Account informations

### ISSUE THREAD

**Issue by madara19** [AlexCSDev/PatreonDownloader#41]
Hello
Where should i input my account login and password please ?

**Comment by madara19** [comment]
PatreonDownloader.App.exe --url https://www.patreon.com/****

2021-01-19 13:22:23.6044 INFO Retrieving cookies...
2021-01-19 13:23:10.0969 FATAL Fatal error, application will be closed: System.Exception: Unable to retrieve cookies
   at PatreonDownloader.App.Program.RunPatreonDownloader(String url, Boolean headlessBrowser, Uri remoteBrowserAddress, PatreonDownloaderSettings settings) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 141
   at PatreonDownloader.App.Program.Main(String[] args) in E:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 74

**Comment by AlexCSDev** [comment]
Internal browser with patreon login page should show up if login is required.
