### ISSUE TITLE
Campaign cover url cannot be null or empty

### ISSUE THREAD

**Issue by pMens-DC** [AlexCSDev/PatreonDownloader#46]
I get this error when trying to use this tool. When using no-headless parameter I can see that images aren't loading correctly in the browser. I don't know what can be causing this issue.
Command line and messages received after: 
PatreonDownloader.App.exe --url https://www.patreon.com/someone/posts --descriptions true --no-headless
2021-02-21 13:29:12.8628 INFO Retrieving cookies...
2021-02-21 13:29:20.3901 INFO Preparing to download...
2021-02-21 13:29:21.4686 INFO Retrieving campaign information...
2021-02-21 13:29:26.9974 INFO Crawling...
2021-02-21 13:29:27.0432 FATAL Fatal error, application will be closed: System.ArgumentException: Campaign cover url cannot be null or empty
   at PatreonDownloader.Engine.Stages.Crawling.PageCrawler.Crawl(CampaignInfo campaignInfo, PatreonDownloaderSettings settings, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\Stages\Crawling\PageCrawler.cs:line 42
   at PatreonDownloader.Engine.PatreonDownloader.Download(String url, PatreonDownloaderSettings settings) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 240
   at PatreonDownloader.App.Program.RunPatreonDownloader(String url, Boolean headlessBrowser, Uri remoteBrowserAddress, PatreonDownloaderSettings settings) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 161
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 74

**Comment by AlexCSDev** [comment]
The images are not supposed to load in the browser to speed up page loading process.

Please post creator's page url here or send it to alexcsdev@protonmail.com so I can take a look at it.

**Comment by AlexCSDev** [comment]
I am closing this issue since I have not received any further information
