### ISSUE TITLE
Fatal error when gdrive link unavailable

### ISSUE THREAD

**Issue by zelleux** [AlexCSDev/PatreonDownloader#52]
Instead of just skipping the link when unavailable, the program stops after attempting to download an unavailable file. Because of this, it is impossible for it to ever finish.

2021-04-03 09:21:57.5200 ERROR [PatreonDownloader.GoogleDriveDownloader.Plugin] GOOGLE DRIVE ERROR: The service drive has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
File not found: 1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI. [404]
Errors [
    Message[File not found: 1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI.] Location[fileId - parameter] Reason[notFound] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.ParseResponse(HttpResponseMessage response)
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at PatreonDownloader.GoogleDriveDownloader.GoogleDriveEngine.Download(String id, String path, Boolean overwrite)
   at PatreonDownloader.GoogleDriveDownloader.Plugin.Download(CrawledUrl crawledUrl, String downloadDirectory)
2021-04-03 09:21:57.5260 FATAL [PatreonDownloader.App.Program] Fatal error, application will be closed: PatreonDownloader.Engine.Exceptions.PatreonDownloaderException: Error while downloading https://drive.google.com/open?id=1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI: Unable to download https://drive.google.com/open?id=1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI
 ---> PatreonDownloader.Common.Exceptions.DownloadException: Unable to download https://drive.google.com/open?id=1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI
 ---> The service drive has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
File not found: 1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI. [404]
Errors [
    Message[File not found: 1HvIsC6MDN6kTXm1Ca9q_CTS8TvHseMyI.] Location[fileId - parameter] Reason[notFound] Domain[global]
]

I don't know if this happens with dropbox or mega either, but it would be appreciated if it just skips them if they don't dl.

**Comment by WindedHero** [comment]
I have also encountered this bug. cancels the entire job with a crash if it encounters a "file not found" error. Any ETA for a fix?

**Comment by AlexCSDev** [comment]
No, there is no ETA. 

If anyone wants to work on this issue feel free to submit PR with the fix.
