### ISSUE TITLE
encounter a Cookie validation failed: cfduid cookie not found

### ISSUE THREAD

**Issue by 35chi** [AlexCSDev/PatreonDownloader#55]
2021-05-11 20:02:27.8874 FATAL [PatreonDownloader.Engine.PatreonDownloader] Cookie validation failed: PatreonDownloader.Engine.Exceptions.CookieValidationException: __cfduid cookie not found
   at PatreonDownloader.Engine.Stages.Initialization.CookieValidator.ValidateCookies(CookieContainer cookieContainer) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\Stages\Initialization\CookieValidator.cs:line 33
   at PatreonDownloader.Engine.PatreonDownloader.Download(String url, PatreonDownloaderSettings settings) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Engine\PatreonDownloader.cs:line 194

command: PatreonDownloader.App.exe --url https://www.patreon.com/xxx/posts --download-directory C:\Users\This-PC\Pictures --descriptions --embeds --campaign-images --json

**Comment by meliamne** [comment]
same here

**Comment by AlexCSDev** [comment]
[Starting with may 10th __cfduid cookie is no longer used by cloudflare](https://blog.cloudflare.com/deprecating-cfduid-cookie/).

I will release hotfix later today to remove check for this cookie's presence.

**Comment by 35chi** [comment]
Thanks mate

**Comment by AlexCSDev** [comment]
Fixed in 0.9.4.2
