### ISSUE TITLE
zsh: no matches found error mac os x

### ISSUE THREAD

**Issue by frranck** [AlexCSDev/PatreonDownloader#58]
Hello,
I'm getting this error on OS X:

```
franck@Admins-MacBook-Pro PatreonDownloader.App % dotnet run --url https://www.patreon.com/user/posts?u=27022 --verbose

zsh: no matches found: https://www.patreon.com/user/posts?u=27022
```
Any idea?

**Comment by AlexCSDev** [comment]
This is definitely not an error PatreonDownloader can return. Something else (zsh?) in your system returns that error.

Try building the app with **dotnet build -c release** and then running "**dotnet PatreonDownloader.App.dll --url https://www.patreon.com/user/posts?u=27022 --verbose**" command in **PatreonDownloader.App\bin\Release\netcoreapp3.1** directory

**Comment by frranck** [comment]
```
franck@Admins-MacBook-Pro PatreonDownloader.App %  dotnet build -c release
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  PatreonDownloader.Common -> /Users/franck/dev/PatreonDownloader/PatreonDownloader.Common/bin/release/netstandard2.1/PatreonDownloader.Common.dll
  PatreonDownloader.PuppeteerEngine -> /Users/franck/dev/PatreonDownloader/PatreonDownloader.PuppeteerEngine/bin/release/netstandard2.1/PatreonDownloader.PuppeteerEngine.dll
DefaultPlugin.cs(178,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/PatreonDownloader.Engine.csproj]
DefaultPlugin.cs(184,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/PatreonDownloader.Engine.csproj]
  PatreonDownloader.Engine -> /Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/bin/release/netcoreapp3.1/PatreonDownloader.Engine.dll
Program.cs(65,30): warning CS0168: The variable 'ex' is declared but never used [/Users/franck/dev/PatreonDownloader/PatreonDownloader.App/PatreonDownloader.App.csproj]
  PatreonDownloader.App -> /Users/franck/dev/PatreonDownloader/PatreonDownloader.App/bin/release/netcoreapp3.1/PatreonDownloader.App.dll

Build succeeded.

DefaultPlugin.cs(178,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/PatreonDownloader.Engine.csproj]
DefaultPlugin.cs(184,41): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/PatreonDownloader.Engine.csproj]
Program.cs(65,30): warning CS0168: The variable 'ex' is declared but never used [/Users/franck/dev/PatreonDownloader/PatreonDownloader.App/PatreonDownloader.App.csproj]
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.82
franck@Admins-MacBook-Pro PatreonDownloader.App % dotnet PatreonDownloader.App.dll --url https://www.patreon.com/user/posts?u=27022 --verbose
zsh: no matches found: https://www.patreon.com/user/posts?u=27022
franck@Admins-MacBook-Pro PatreonDownloader.App % cd bin
franck@Admins-MacBook-Pro bin % cd release 
franck@Admins-MacBook-Pro release % ls
netcoreapp3.1
franck@Admins-MacBook-Pro release % cd netcoreapp3.1 
franck@Admins-MacBook-Pro netcoreapp3.1 % dotnet PatreonDownloader.App.dll --url https://www.patreon.com/user/posts?u=27022 --verbose
zsh: no matches found: https://www.patreon.com/user/posts?u=27022
franck@Admins-MacBook-Pro netcoreapp3.1 % pwd
/Users/franck/dev/PatreonDownloader/PatreonDownloader.App/bin/release/netcoreapp3.1

```

**Comment by frranck** [comment]
I tried to run it from bash, it is working. zsh is the new default in OSX thought. weird Isn't it?

**Comment by frranck** [comment]
I'm getting thos errors afterwards 

```
 is too long, or a component of the specified path is too long.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at PatreonDownloader.Engine.WebDownloader.DownloadFile(String url, String path, Boolean overwrite) in /Users/franck/dev/PatreonDownloader/PatreonDownloader.Engine/WebDownloader.cs:line 74

```

although I added a --download-directory /Users/franck/Downloads/

**Comment by AlexCSDev** [comment]
I'm not really sure what's going on. As I don't have any access to mac computer I'm afraid I can't really figure out what is going on.

I will keep this open and tag it as "help wanted" in case someone with mac can figure this out.

**Comment by frranck** [comment]
OK thanks, I will try on a windows or linux.

**Comment by disco0** [comment]
Little bit late, but for future reference—`?` is a glob operator, which should be escaped or quoted to avoid triggering and failing to match a file name. Its also very common in urls, which is unfortunate.

Some examples of usage below, assuming `dotnet` is a command on `PATH`:

``` zsh

# Temporarilty make dotnet command just show arguments passed in, just for demonstration purposes
function dotnet() { builtin print -u2 -- $^@ } 

{

# Invalid: As invoked in issue
dotnet run --url https://www.patreon.com/user/posts?u=27022 --verbose

# Escaping globbing character
dotnet run --url https://www.patreon.com/user/posts\?u=27022 --verbose

# Quoting globbing character
dotnet run --url "https://www.patreon.com/user/posts?u=27022" --verbose

# Using the noglob precommand modifier
noglob dotnet run --url https://www.patreon.com/user/posts?u=27022 --verbose

} always { unfunction dotnet }

```

Only the first command should error out.

I believe `bracketed-paste-url-magic` can handle this automatically when pasting text as well.

**Comment by geekwho-eth** [comment]
This works for me.
# How to build PatreonDownloader on macOS.
just follow these steps:

`
## clone git repo
git clone https://github.com/AlexCSDev/PatreonDownloader.git
cd PatreonDownloader
## update repo code
git submodule init
git submodule update

## install dotnet
brew install dotnet@8
echo 'export PATH="/opt/homebrew/opt/dotnet@8/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
dotnet --info
.NET SDK:
 Version:           8.0.111
 Commit:            ad116b5ce0
 Workload version:  8.0.100-manifests.7198dcc9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.2
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet@8/8.0.11/libexec/sdk/8.0.111/

.NET workload installed:
 Workload version: 8.0.100-manifests.7198dcc9
There are no installed workloads to display.

Host:
  Version:      8.0.11
  Architecture: arm64
  Commit:       9cb3b725e3

.NET SDKs installed:
  8.0.111 [/opt/homebrew/Cellar/dotnet@8/8.0.11/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [/opt/homebrew/Cellar/dotnet@8/8.0.11/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [/opt/homebrew/Cellar/dotnet@8/8.0.11/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/Cellar/dotnet@8/8.0.11/libexec]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

cd PatreonDownloader.App
cd bin/Release/net8.0/
dotnet PatreonDownloader.App.dll --url https://www.patreon.com/user/posts\?u\=27022
`

**Comment by Queilow** [comment]
The above works but you need to call `dotnet build -c release` before you can `cd bin/Release/net8.0/`

**Comment by geekwho-eth** [comment]
> The above works but you need to call `dotnet build -c release` before you can `cd bin/Release/net8.0/`

Got it fixed!
Thanks, bro.
