### ISSUE TITLE
Unable to retrieve campaign id

### ISSUE THREAD

**Issue by lacafjh** [AlexCSDev/PatreonDownloader#81]
```
PS X:\Patreon Downloader\net5.0-win-x64-release> .\PatreonDownloader.App.exe --url https://www.patreon.com/Mushi024/posts --embeds --download-directory "X:\Patreon Downloader"
2021-09-16 15:58:24.6252 INFO Retrieving cookies...
2021-09-16 16:00:23.4145 INFO Preparing to download...
2021-09-16 16:00:24.1681 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve campaign id: Unable to retrieve data from https://www.patreon.com/mushi024/posts: Error status code returned: Forbidden
 ---> UniversalDownloaderPlatform.Common.Exceptions.DownloadException: Unable to retrieve data from https://www.patreon.com/mushi024/posts: Error status code returned: Forbidden
 ---> System.Net.WebException: Error status code returned: Forbidden
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadStringInternal(String url, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 295
   --- End of inner exception stack trace ---
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadStringInternal(String url, Int32 retry, Int32 retryTooManyRequests) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 341
   at UniversalDownloaderPlatform.DefaultImplementations.WebDownloader.DownloadString(String url) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\WebDownloader.cs:line 260
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 36
   --- End of inner exception stack trace ---
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.GetCampaignId(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 49
   at PatreonDownloader.Implementation.PatreonCrawlTargetInfoRetriever.RetrieveCrawlTargetInfo(String url) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawlTargetInfoRetriever.cs:line 24
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 171
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 148
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 74
```

My operation environment:
> Windows 10 Enterprise
> 19043.1165
> Windows Feature Experience Pack 120.2212.3530.0

**Comment by AlexCSDev** [comment]
Tried running the app on more or less similar OS build. Runs fine on my side.

Judging by the error you are probably blocked by cloudflare, I can only recommend you to try changing your ip address by rebooting your router if you have dynamic ip or using vpn.

I can't really do anything about this, sorry.
