### ISSUE TITLE
Fatal error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#88]
`2021-10-03 10:52:41.2348 FATAL Fatal error, application will be closed: System.NullReferenceException: Object reference not set to an instance of an object.
   at PatreonDownloader.Implementation.PostSubdirectoryHelper.CreateNameFromPattern(PatreonCrawledUrl crawledUrl, String pattern) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\Helpers\PostSubdirectoryHelper.cs:line 23
   at PatreonDownloader.Implementation.PatreonPageCrawler.ParsePage(String json, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 155
   at PatreonDownloader.Implementation.PatreonPageCrawler.Crawl(ICrawlTargetInfo crawlTargetInfo, String downloadDirectory) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.Implementation\PatreonPageCrawler.cs:line 92
   at UniversalDownloaderPlatform.Engine.UniversalDownloader.Download(String url, String downloadDirectory, IUniversalDownloaderPlatformSettings settings) in F:\Sources\BigProjects\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloader.cs:line 198
   at PatreonDownloader.App.Program.RunPatreonDownloader(CommandLineOptions commandLineOptions) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 143
   at PatreonDownloader.App.Program.Main(String[] args) in F:\Sources\BigProjects\PatreonDownloader\PatreonDownloader.App\Program.cs:line 69`

App crashes before downloading any media. Only files downloaded are page.json, description.html, and embed.txt in post subfolders.

**Comment by AlexCSDev** [comment]
Please send page*.json files to alexcsdev@protonmail.com so I can take a look why this happens.

**Comment by AlexCSDev** [comment]
Fixed in 0.10.1.1
