### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#89]
`DEBUG Encountered error while trying to download ###, retrying in 20 seconds (0 retries left)... The error is: System.IO.DirectoryNotFoundException: Could not find a part of the path '###'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at CG.Web.MegaApiClient.MegaApiClient.SaveStream(Stream stream, String outputFile)
   at CG.Web.MegaApiClient.MegaApiClient.<>c__DisplayClass80_0.<DownloadFileAsync>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UniversalDownloaderPlatform.MegaDownloader.MegaDownloader.DownloadFileAsync(INode fileNode, Uri fileUri, INodeInfo fileNodeInfo, String path, Boolean overwrite, Int32 retry)`

**Comment by AlexCSDev** [comment]
Can't replicate this yet. Can you also send me the log file from logs folder?

**Comment by WindedHero** [comment]
Sent!

**Comment by AlexCSDev** [comment]
Thank you.

That's really weird, not sure what's going on. It's a bit late, so I'll take a closer look tomorrow.

**Comment by AlexCSDev** [comment]
Fixed in 0.10.1.1
